name: release zbyte-common

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

jobs:
  code-quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: 'npm'
          registry-url: https://npm.pkg.github.com
          scope: '@zbyteio'
      - name: Clean Install NPM modules
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.FORCI}}
      - name: Verify code format
        run: npm run check-fmt
      - name: Check code lint
        run: npm run lint
      - name: Build zbyte-common lib
        run: npm run build
      - name: Execute Tests
        run: npm test

  node_module_publish:
    needs: code-quality-check
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: 'npm'
          registry-url: https://npm.pkg.github.com
          scope: '@zbyteio'
      - name: Version
        run: |
          version=$(echo ${{ github.ref_name }} | cut -d'v' -f2)
          echo "The tagged version is $version"
          jq ".version = \"$version\"" package.json > /tmp/file && mv /tmp/file package.json 
      - name: Clean Install NPM modules
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Build zbyte-common lib
        run: npm run build
      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
